# Exported from Render on 2024-12-17T15:24:18Z
services:
- type: web
  name: mysite
  runtime: ruby
  repo: https://github.com/santiagocherrys/rails_tutorial_chapter1
  plan: free
  envVars:
  - key: WEB_CONCURRENCY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec rails server
version: "1"
